# Generated by Django 4.1.2 on 2022-10-23 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_position_delete_fireexquainorder_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Позиция', 'verbose_name_plural': 'Позиции'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='fire_extingushers',
            new_name='positions',
        ),
        migrations.AlterField(
            model_name='position',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.order', verbose_name='партия'),
        ),
    ]
